database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ecommerce
  sslmode: disable

cache:
  addr: "localhost:6379"
  password: ""
  db: 0

minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  use_ssl: false
  bucket_name: "products"
